"""Add WO Title field and format suggested actions as numbered list."""
path = "/root/ASSET-MANAGEMENT-SOFTWARE/frontend/src/pages/FailureCapture.jsx"
with open(path, "r") as f:
    c = f.read()

# 1. Add woTitle to form state
c = c.replace(
    "suggestedAction: '', estimatedDuration: '', priority: 'P3', activityClass: 'M001',",
    "woTitle: '', suggestedAction: '', estimatedDuration: '', priority: 'P3', activityClass: 'M001',"
)

# 2. Add WO Title field before "What happened?"
old_what = """          {/* 1. What happened? + Voice / Camera */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <label className="text-xs font-semibold text-gray-500 uppercase tracking-wider">What happened?</label>"""

new_what = """          {/* 0. WO Title - auto-generated by AI */}
          <div className="border rounded-xl p-4 bg-emerald-50/30">
            <label className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2 block">WO TITLE / CASE NAME</label>
            <input
              type="text"
              value={form.woTitle}
              onChange={e => setF('woTitle', e.target.value)}
              placeholder="Auto-generated by AI Assist (e.g. 'Pump bearing replacement P-3201A')"
              className="w-full px-3 py-2.5 border border-emerald-300 rounded-xl text-sm font-semibold focus:outline-none focus:ring-2 focus:ring-emerald-500/30 bg-white"
            />
            <p className="text-[10px] text-gray-400 mt-1">This will be the Work Order name in Planning and Identification</p>
          </div>

          {/* 1. What happened? + Voice / Camera */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <label className="text-xs font-semibold text-gray-500 uppercase tracking-wider">What happened?</label>"""

c = c.replace(old_what, new_what)

# 3. AI Assist sets woTitle from enhanced_description
# When AI returns results, auto-generate a title
c = c.replace(
    "if (s.suggestedAction || s.suggested_action) setF('suggestedAction', s.suggestedAction || s.suggested_action);",
    """if (s.suggestedAction || s.suggested_action) setF('suggestedAction', s.suggestedAction || s.suggested_action);
        // Auto-generate WO title from AI
        if (s.enhanced_description) {
          const desc = s.enhanced_description;
          // Extract first sentence or create short title
          const title = desc.split('.')[0].substring(0, 100);
          setF('woTitle', title);
        }"""
)

# 4. Format suggestedAction - replace textarea with formatted display
# Replace the suggested action textarea to show as numbered list
old_suggestion = """            <textarea value={form.suggestedAction} onChange={e => setF('suggestedAction', e.target.value)}
              placeholder="What corrective action is recommended?"
              rows={4} className="w-full px-3 py-2.5 border border-gray-300 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500/30 resize-y" />"""

new_suggestion = """            {form.suggestedAction && /\\d+[\\.\\)]/.test(form.suggestedAction) ? (
              <div className="space-y-1.5 mb-2">
                {form.suggestedAction.split(/(?=\\d+[\\.\\)])/).filter(s => s.trim()).map((step, i) => (
                  <div key={i} className="flex gap-2 p-2 bg-gray-50 rounded-lg border text-xs">
                    <span className="font-bold text-emerald-600 min-w-[20px]">{i+1}.</span>
                    <span>{step.replace(/^\\d+[\\.\\)]\\s*/, '').trim()}</span>
                  </div>
                ))}
              </div>
            ) : null}
            <textarea value={form.suggestedAction} onChange={e => setF('suggestedAction', e.target.value)}
              placeholder="What corrective action is recommended?"
              rows={form.suggestedAction && /\\d+[\\.\\)]/.test(form.suggestedAction) ? 2 : 4}
              className="w-full px-3 py-2.5 border border-gray-300 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500/30 resize-y" />"""

c = c.replace(old_suggestion, new_suggestion)

# 5. Include woTitle in the WR submission
c = c.replace(
    "suggested_action: form.suggestedAction || '',",
    "suggested_action: form.suggestedAction || '',\n        wo_title: form.woTitle || '',"
)

with open(path, "w") as f:
    f.write(c)
print("Done")
