"""
Catalog API — serves SAP PM reference data extracted from PLANILLAS DE CARGA.

Source: Gold Fields Salares Norte (MGSN) SAP PM data loading templates.
Data files: api/data/*.json (generated by scripts/extract_planillas_carga.py)

Endpoints:
  GET /catalogs/failure-categories          — Discipline-grouped failure catalog (mobile UI)
  GET /catalogs/failure-profiles            — Full catalog by equipment profile (167 profiles)
  GET /catalogs/failure-profile/{code}      — Single profile with causes/symptoms/parts
  GET /catalogs/equipment-types             — 207 SAP equipment type codes
  GET /catalogs/taxonomy                    — Hierarchy nodes from taxonomy
  GET /catalogs/criticality                 — Criticality assessment data
"""

import json
import os
from functools import lru_cache
from fastapi import APIRouter, Query, HTTPException

router = APIRouter(prefix="/catalogs", tags=["catalogs"])

DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data")


@lru_cache(maxsize=8)
def _load_json(filename: str):
    path = os.path.join(DATA_DIR, filename)
    if not os.path.exists(path):
        return None
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


# ── Failure Catalog (discipline-grouped for mobile UI) ──────────────

@router.get("/failure-categories")
def get_failure_categories():
    """Return failure catalog grouped by discipline (Mecánico, Eléctrico, Instrumentación).
    Used by the mobile WR creation form."""
    data = _load_json("failure_catalog_by_discipline.json")
    if not data:
        return []
    result = []
    for key in ["MECANICO", "ELECTRICO", "INSTRUMENTACION"]:
        cat = data.get(key, {})
        result.append({
            "category": key,
            "label": cat.get("label", key),
            "color": cat.get("color", "#6366F1"),
            "symptoms": cat.get("symptoms", []),
            "parts": cat.get("parts", []),
            "causes": cat.get("causes", []),
        })
    return result


# ── Failure Catalog (by equipment profile — full SAP PM) ───────────

@router.get("/failure-profiles")
def get_failure_profiles(search: str = Query(None, description="Search by profile code or name")):
    """Return all failure catalog profiles (167 equipment types).
    Each profile has its own causes, symptoms, and parts."""
    data = _load_json("failure_catalog_sap.json")
    if not data:
        return {"profiles": [], "global_causes": [], "global_symptoms": []}
    profiles = list(data.get("profiles", {}).values())
    if search:
        q = search.lower()
        profiles = [p for p in profiles if q in p["code"].lower() or q in p["name"].lower()]
    return {
        "profiles": profiles,
        "global_causes": data.get("global_causes", []),
        "global_symptoms": data.get("global_symptoms", []),
    }


@router.get("/failure-profile/{code}")
def get_failure_profile(code: str):
    """Return a single failure catalog profile by code."""
    data = _load_json("failure_catalog_sap.json")
    if not data:
        raise HTTPException(404, "Catalog data not available")
    profiles = data.get("profiles", {})
    profile = profiles.get(code.upper()) or profiles.get(code)
    if not profile:
        raise HTTPException(404, f"Profile {code} not found")
    return profile


# ── Equipment Types ─────────────────────────────────────────────────

@router.get("/equipment-types")
def get_equipment_types(search: str = Query(None)):
    """Return 207 SAP equipment type codes with descriptions."""
    data = _load_json("equipment_types_sap.json")
    if not data:
        return []
    result = [{"code": k, "description": v} for k, v in data.items()]
    if search:
        q = search.lower()
        result = [r for r in result if q in r["code"].lower() or q in r["description"].lower()]
    return sorted(result, key=lambda x: x["code"])


# ── Taxonomy ────────────────────────────────────────────────────────

@router.get("/taxonomy")
def get_taxonomy(node_type: str = Query(None), level: int = Query(None)):
    """Return hierarchy nodes extracted from SAP taxonomy."""
    data = _load_json("taxonomy_sap.json")
    if not data:
        return []
    result = data
    if node_type:
        result = [n for n in result if n.get("node_type") == node_type.upper()]
    if level is not None:
        result = [n for n in result if n.get("level") == level]
    return result


# ── Criticality ─────────────────────────────────────────────────────

@router.get("/criticality")
def get_criticality(tag: str = Query(None)):
    """Return criticality assessment data."""
    data = _load_json("criticality_sap.json")
    if not data:
        return []
    if tag:
        q = tag.lower()
        data = [a for a in data if q in a.get("tag", "").lower()]
    return data
